# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      plugins:
        patterns:
          - "*:*-plugins:*"
    ignore:
      - dependency-name: "org.apache.maven.plugins:*"
        versions: ["[4.x,)"] # These are for Maven 4
      - dependency-name: "*"
        update-types: ["version-update:semver-major"] # No MRs for major versions
    open-pull-requests-limit: 100
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
